#!/bin/bash

set -ex

# shellcheck source=config.sh
source /srv/config.sh
if [[ "$ARCH" != amd64 ]]; then
    echo "OVA export is only supported for amd64" >&2
    exit 1
fi

WORKSPACE="/target"
for output in root.vmdk root.vdi \
    "VMware-Xubuntu-$RELEASE-amd64.ova" "VirtualBox-Xubuntu-$RELEASE-amd64.ova"; do
    if [[ -e "$WORKSPACE/$output" || -L "$WORKSPACE/$output" ]]; then
        echo "Refusing to overwrite $WORKSPACE/$output" >&2
        exit 1
    fi
done
test -r "$WORKSPACE/root.qcow2"
command -v vmdk-convert >/dev/null
command -v ova-compose >/dev/null
command -v VBoxManage >/dev/null

# Vmware: convert .img to .vmdk
qemu-img convert -pO vmdk "$WORKSPACE"/root.qcow2 "$WORKSPACE"/root.vmdk

# VirtualBox: convert .img to .vdi
qemu-img convert -pO vdi "$WORKSPACE"/root.qcow2 "$WORKSPACE"/root.vdi

# VMware: package the disk with the declarative hardware description.
bash /srv/assets/export-vmware.sh "$WORKSPACE/root.vmdk" \
    "$WORKSPACE/VMware-Xubuntu-${RELEASE}-amd64.ova"

# VirtualBox: config
VBoxManage createvm --name "VirtualBox-Xubuntu-${RELEASE}-amd64" --ostype "Ubuntu_64" --register
VBoxManage storagectl "VirtualBox-Xubuntu-${RELEASE}-amd64" --name "SATA Controller" --add sata --controller IntelAHCI
VBoxManage storageattach "VirtualBox-Xubuntu-${RELEASE}-amd64" --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium "$WORKSPACE"/root.vdi
VBoxManage modifyvm "VirtualBox-Xubuntu-${RELEASE}-amd64" --memory 2048 --cpus 2
VBoxManage modifyvm "VirtualBox-Xubuntu-${RELEASE}-amd64" --boot1 disk --boot2 none --boot3 none --boot4 none --rtcuseutc on --firmware efi
VBoxManage modifyvm "VirtualBox-Xubuntu-${RELEASE}-amd64" --mouse usbtablet --vram 32 --usb on --usbehci on
VBoxManage modifyvm "VirtualBox-Xubuntu-${RELEASE}-amd64" --nic1 nat
VBoxManage modifyvm "VirtualBox-Xubuntu-${RELEASE}-amd64" --pae off --longmode on --x2apic on --largepages on
VBoxManage modifyvm "VirtualBox-Xubuntu-${RELEASE}-amd64" --graphicscontroller vmsvga
VBoxManage modifyvm "VirtualBox-Xubuntu-${RELEASE}-amd64" --vram 128
VBoxManage modifyvm "VirtualBox-Xubuntu-${RELEASE}-amd64" --accelerate3d on


# VirtualBox: export ova
VBoxManage export "VirtualBox-Xubuntu-${RELEASE}-amd64" --output "$WORKSPACE/VirtualBox-Xubuntu-${RELEASE}-amd64.ova"

# Update permission
chmod 644 "$WORKSPACE"/*.ova

bash /srv/101strap_checksums "$WORKSPACE"

# Delete .qcow2
# rm -f "$WORKSPACE"/root.qcow2
