#!/bin/bash

set -e

WORKSPACE="/target"

# Vmware: convert .img to .vmdk
qemu-img convert -pO vmdk "$WORKSPACE"/root.img "$WORKSPACE"/root.vmdk
# VirtualBox: convert .img to .vdi
qemu-img convert -pO vdi "$WORKSPACE"/root.img "$WORKSPACE"/root.vdi

# Delete .img
# rm -f "$WORKSPACE"/root.img
